name: Update and Deploy Date Map

on:
  push:
    paths:
      - 'MyDateWidget/markers.json'
      - 'MyDateWidget/MyDateWidget.html'
      - '.github/workflows/naverMap.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: naverMap

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace Naver Map secrets
        run: |
          sed -i 's/%NAVERMAPID%/${{ secrets.NAVERMAPID }}/g' MyDateWidget/MyDateWidget.html
          sed -i 's/%NAVERMAPKEY%/${{ secrets.NAVERMAPKEY }}/g' MyDateWidget/MyDateWidget.html

      - name: Copy to index.html for GitHub Pages
        run: cp MyDateWidget/MyDateWidget.html MyDateWidget/index.html

      - name: Commit replaced files
        run: |
          git add MyDateWidget/MyDateWidget.html MyDateWidget/index.html
          git commit -m "Apply NaverMap secrets and set index.html" || echo "No changes to commit"
          git push
          
      - name: Deploy MyDateWidget folder to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./MyDateWidget
