name: Update Lost Ark Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * *'  # 매일 KST 0시 (UTC 기준 15시)
  workflow_dispatch:      # 수동 실행도 가능하게

jobs:
  fetch-lostark-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch data from LostArk API
      run: |
        curl -H "Authorization: Bearer ${{ secrets.LOSTARK_API_KEY }}" \
          https://developer-lostark.game.onstove.com/news/notices \
          -o LoskArkWidget/data.json

    - name: Commit and push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add public/data.json
        git commit -m "Update Lost Ark data"
        git push
